export const MODAL_KEYS = {
  CONFERENCE_DETAILS: 'CONFERENCE_DETAILS',
  CONFERENCE_CREATE: 'CONFERENCE_CREATE',
  GUEST_DETAILS: 'GUEST_DETAILS',
  GUEST_CREATE: 'GUEST_CREATE',
  PAGE_BLOCK_EDITOR: 'PAGE_BLOCK_EDITOR',
} as const;

export type ModalKey = (typeof MODAL_KEYS)[keyof typeof MODAL_KEYS];
